CREATE DATABASE IF NOT EXISTS altilier

CREATE TABLE IF NOT EXISTS reviews (
  review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id int NOT NULL,
  rating SMALLINT NOT NULL,
  date date NOT NULL,
  summary varchar (50) NOT NULL,
  body varchar (1002) NOT NULL,
  recommend varchar(5) not null,
  reported varchar(5) NOT NULL,
  reviewer_name varchar(40) NOT NULL,
  reviewer_email varchar(320) NOT NULL,
  response varchar(500) DEFAULT null,
  helpfulness int DEFAULT 0
);

CREATE INDEX product_idx ON reviews (product_id);

CREATE TABLE IF NOT EXISTS p (
  id SERIAL NOT NULL PRIMARY KEY,
  photo_id int NOT NULL,
  review_id int NOT NULL,
  url varchar(255)
);

CREATE TABLE IF NOT EXISTS photos (
  id SERIAL NOT NULL PRIMARY KEY,
  photo_id int NOT NULL,
  review_id int NOT NULL,
  url varchar(255),
  FOREIGN KEY (review_id) REFERENCES reviews(review_id)
);


 CREATE TABLE characteristics (
  characteristic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT NOT NULL,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE c_reviews (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  characteristic_id INT NOT NULL,
  review_id INT NOT NULL,
  rating SMALLINT NOT NULL,
  FOREIGN KEY (characteristic_id) REFERENCES characteristics (characteristic_id)
);

CREATE INDEX c_id ON c_reviews (characteristic_id);

CREATE INDEX p_idx on characteristics (product_id);



